---
- include_tasks: "install_{{ ansible_distribution }}.yml"
  tags: always

# Run distribution-specific tasks
- include_tasks: "{{include_item}}"
  with_first_found:
    - files:
        - "install_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      paths:
        - "../tasks"
      skip: yes
  loop_control:
    loop_var: include_item
  tags: always

- name: Check for required variables
  assert:
    that:
      - haproxy_conf_path is defined
      - haproxy_bin_path is defined
      - haproxy_logrotate_conf_path is defined

- name: Create haproxy ssl directory
  file:
    path: /etc/ssl/haproxy
    state: directory

- include_tasks: "interfaces_{{ ansible_os_family }}.yml"
  when: haproxy_manage_ips|bool

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf_path }}"
    trim_blocks: yes
    lstrip_blocks: yes
    backup: yes
    validate: "{{ haproxy_bin_path }} -c -V -f %s"
  notify: reload haproxy
  register: haproxy_conf_res
  ignore_errors: yes
  tags: haproxy_conf

- name: Dump failed template to /root/haproxy_failed.conf
  template:
    src: haproxy.cfg.j2
    dest: /root/haproxy_failed.conf
    trim_blocks: yes
    lstrip_blocks: yes
  when: haproxy_conf_res.failed
  tags: haproxy_conf

- name: Abort if proxy configuration failed
  fail: msg="Configuration failed"
  when: haproxy_conf_res.failed
  tags: haproxy_conf

- name: Configure rsyslog for haproxy logging
  template:
    src: rsyslog_haproxy.j2
    dest: /etc/rsyslog.d/haproxy.conf
  notify: restart rsyslog
  tags: haproxy_conf

- name: Configure log rotation
  template:
    src: haproxy_logrotate.j2
    dest: "{{ haproxy_logrotate_conf_path }}"
